# Generated by Django 6.0.5 on 2026-05-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(default='SS-S01', max_length=20),
            preserve_default=False,
        ),
    ]
