# Generated by Django 6.0.5 on 2026-06-08 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_productcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='selected_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
